build-api:
  stage: build
  image: docker:latest
  services:
    - docker:19.03.13-dind
  tags: ['docker']
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd api
    - docker build -t $CI_REGISTRY_IMAGE:api .
    - docker push $CI_REGISTRY_IMAGE:api

build-bot:      
  stage: build
  image: docker:latest
  services:
    - docker:19.03.13-dind
  tags: ['docker']
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd bot
    - docker build -t $CI_REGISTRY_IMAGE:bot .
    - docker push $CI_REGISTRY_IMAGE:bot

build-ui:
  stage: build
  image: docker:latest
  services:
    - docker:19.03.13-dind
  tags: ['docker']
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - cd ui
    - docker build -t $CI_REGISTRY_IMAGE:ui .
    - docker push $CI_REGISTRY_IMAGE:ui

test-api:
  stage: test
  needs: [build-api]
  image: $CI_REGISTRY_IMAGE:api
  script:
    - sh /opt/app/run_tests.sh

test-bot:
  stage: test
  needs: [build-bot]
  image: $CI_REGISTRY_IMAGE:bot
  script:
    - sh /opt/app/run_tests.sh

test-ui:
  stage: test
  needs: [build-ui]
  image: $CI_REGISTRY_IMAGE:ui
  script:
    - echo "ui tests"

deploy-prod:
  stage: deploy
  needs: [test-bot, test-api, test-ui]
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
