version: "3.5"
services:
    botcman__ui:
        restart: always
        container_name: botcman__ui
        build:
            context: .
            dockerfile: Dockerfile
        image: botcman__ui:latest
        networks:
            - intercom
networks:
    intercom:
        external: True
